repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        args: [
            '--line-length=120',
            '--multi-line=3',
            '--force-grid-wrap=0',
            '--trailing-comma',
            '--use-parentheses',
            '--ensure-newline-before-comments',
        ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        args: [
            '--max-line-length=120',
            "--per-file-ignores=__init__.py:F401",
        ]
      - id: pytest
        name: pytest
        entry: ./pre-commit/run_pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true